//! End-to-end: a [`TarsAgent`] runs a [`Task`] over a mock provider,
//! driving a real tars-tools loop — and the `AgentContext::cwd` set at the
//! task level lands in the tool, so a relative write resolves inside the
//! scoped worktree (NOT the process cwd). This is the proof the cwd seam
//! threads model → native agent → WorkerAgent → ToolContext.

use std::sync::{Arc, Mutex};

use async_trait::async_trait;
use futures::stream;

use tars_agent::{Agent, AgentContext, Permissions, Skill, SkillSet, Task, TaskId};
use tars_pipeline::{LlmService, Pipeline, ProviderService};
use tars_provider::{LlmEventStream, LlmProvider};
use tars_runtime::TarsAgent;
use tars_tools::{ToolRegistry, builtins::WriteFileTool};
use tars_types::{
    Capabilities, ChatEvent, ChatRequest, Pricing, ProviderError, ProviderId, RequestContext,
    StopReason, Usage,
};

// ── Mock provider: one canned ChatEvent sequence per call ────────────────

struct EventQueueProvider {
    id: ProviderId,
    capabilities: Capabilities,
    queue: Mutex<std::collections::VecDeque<Vec<ChatEvent>>>,
}

impl EventQueueProvider {
    fn new(sequences: Vec<Vec<ChatEvent>>) -> Arc<Self> {
        Arc::new(Self {
            id: ProviderId::new("event_queue_mock"),
            capabilities: Capabilities::text_only_baseline(Pricing::default()),
            queue: Mutex::new(sequences.into_iter().collect()),
        })
    }
}

#[async_trait]
impl LlmProvider for EventQueueProvider {
    fn id(&self) -> &ProviderId {
        &self.id
    }
    fn capabilities(&self) -> &Capabilities {
        &self.capabilities
    }
    async fn stream(
        self: Arc<Self>,
        _req: ChatRequest,
        _ctx: RequestContext,
    ) -> Result<LlmEventStream, ProviderError> {
        let next = self
            .queue
            .lock()
            .unwrap()
            .pop_front()
            .ok_or_else(|| ProviderError::Internal("queue empty".into()))?;
        let mapped: Vec<Result<ChatEvent, ProviderError>> = next.into_iter().map(Ok).collect();
        Ok(Box::pin(stream::iter(mapped)))
    }
}

fn build_llm(provider: Arc<EventQueueProvider>) -> Arc<dyn LlmService> {
    let inner: Arc<dyn LlmService> = ProviderService::new(provider);
    Arc::new(Pipeline::builder_with_inner(inner).build())
}

fn tool_call_events(call_id: &str, tool: &str, args: serde_json::Value) -> Vec<ChatEvent> {
    vec![
        ChatEvent::started("any-model"),
        ChatEvent::ToolCallStart {
            index: 0,
            id: call_id.to_string(),
            name: tool.to_string(),
        },
        ChatEvent::ToolCallEnd {
            index: 0,
            id: call_id.to_string(),
            parsed_args: args,
            thought_signature: None,
        },
        ChatEvent::Finished {
            stop_reason: StopReason::ToolUse,
            usage: Usage {
                input_tokens: 40,
                output_tokens: 8,
                ..Default::default()
            },
        },
    ]
}

fn final_text_events(text: &str) -> Vec<ChatEvent> {
    vec![
        ChatEvent::started("any-model"),
        ChatEvent::Delta {
            text: text.to_string(),
        },
        ChatEvent::Finished {
            stop_reason: StopReason::EndTurn,
            usage: Usage {
                input_tokens: 25,
                output_tokens: 10,
                ..Default::default()
            },
        },
    ]
}

#[tokio::test]
async fn tars_agent_runs_a_task_and_tool_writes_into_the_cwd() {
    let dir = tempfile::tempdir().unwrap();

    // The agent's one capability: write files, jailed to the worktree.
    let mut reg = ToolRegistry::new();
    reg.register_owned(WriteFileTool::with_root(dir.path()).unwrap())
        .unwrap();
    let tools = Arc::new(reg);

    // Model: turn 1 writes a file via a RELATIVE path, turn 2 reports.
    let final_json = serde_json::json!({
        "summary": "wrote out.txt",
        "confidence": 0.95
    })
    .to_string();
    let provider = EventQueueProvider::new(vec![
        tool_call_events(
            "call_1",
            "fs.write_file",
            serde_json::json!({ "path": "out.txt", "content": "generated by the agent" }),
        ),
        final_text_events(&final_json),
    ]);
    let llm = build_llm(provider);

    let agent = TarsAgent::new(
        "agent:coder",
        "fix",
        SkillSet::new().with(Skill::new("fs.write_file", "writes files")),
        "any-model",
        llm,
        tools,
    );

    // Task-level interface: a goal + the worktree as cwd.
    let task = Task::new(TaskId::new("t-1"), "create out.txt with some content");
    let ctx = AgentContext::new().with_cwd(dir.path());

    let out = agent.run(task, ctx).await.expect("agent should finish");

    // The agent reported its result.
    assert_eq!(out.summary, "wrote out.txt");
    let conf = out
        .data
        .as_ref()
        .and_then(|d| d.get("confidence"))
        .and_then(|c| c.as_f64())
        .expect("confidence present");
    assert!((conf - 0.95).abs() < 1e-4, "confidence ≈ 0.95, got {conf}");

    // THE PROOF: the relative write landed inside the cwd we set at the
    // task level — the cwd threaded model → TarsAgent → WorkerAgent →
    // ToolContext, not the process cwd.
    let written = dir.path().join("out.txt");
    assert!(
        written.exists(),
        "out.txt must exist inside the agent's cwd"
    );
    assert_eq!(
        std::fs::read_to_string(&written).unwrap(),
        "generated by the agent"
    );

    // And the agent advertises its capability.
    assert!(agent.skills().contains("fs.write_file"));
    assert_eq!(agent.role().kind(), "worker");
}

#[tokio::test]
async fn a_denied_skill_never_runs_the_tool() {
    let dir = tempfile::tempdir().unwrap();
    let mut reg = ToolRegistry::new();
    reg.register_owned(WriteFileTool::with_root(dir.path()).unwrap())
        .unwrap();
    let tools = Arc::new(reg);

    // Same 2-turn script: the model tries to write, then reports.
    let final_json = serde_json::json!({ "summary": "tried", "confidence": 0.5 }).to_string();
    let provider = EventQueueProvider::new(vec![
        tool_call_events(
            "call_1",
            "fs.write_file",
            serde_json::json!({ "path": "blocked.txt", "content": "should not exist" }),
        ),
        final_text_events(&final_json),
    ]);
    let agent = TarsAgent::new(
        "agent:coder",
        "fix",
        SkillSet::new().with(Skill::new("fs.write_file", "writes files")),
        "any-model",
        build_llm(provider),
        tools,
    );

    // Permissions DENY the write skill.
    let ctx = AgentContext::new()
        .with_cwd(dir.path())
        .with_permissions(Permissions::default().deny("fs.write_file"));

    let out = agent
        .run(Task::new(TaskId::new("t-2"), "write blocked.txt"), ctx)
        .await
        .expect("agent still completes (the model adapts to the refusal)");
    assert_eq!(out.summary, "tried");

    // THE PROOF: the tool never ran — the permission gate refused it
    // before dispatch, so no file landed.
    assert!(
        !dir.path().join("blocked.txt").exists(),
        "denied skill must not have written the file"
    );
}

/// `TarsAgent` is ALSO a `Worker`: registered in a `WorkerRegistry` and
/// scheduled by `run_plan`, the SAME type the tests above hand a `Task` runs
/// a `PlanStep` to completion. One type is both Agent and Worker — no separate
/// per-step worker wrapper. (Proves the P1 bridge of the arc agent-pipeline
/// unification: `docs/architecture` / arc `agent-pipeline-unification`.)
#[tokio::test]
async fn tars_agent_is_also_a_worker_scheduled_by_run_plan() {
    use tars_runtime::{
        run_plan, LocalRuntime, Plan, PlanStep, RunPlanConfig, Runtime, StepCondition,
        StepOutcome, WorkerRegistry,
    };
    use tars_storage::{EventStore, SqliteEventStore};
    use tokio_util::sync::CancellationToken;

    // One pure-inference turn: the worker JSON the step parses into a result.
    let provider = EventQueueProvider::new(vec![final_text_events(
        &serde_json::json!({ "summary": "reviewed lib.rs", "confidence": 0.9 }).to_string(),
    )]);
    let agent = TarsAgent::new(
        "agent:critic",
        "review",
        SkillSet::new(),
        "any-model",
        build_llm(provider),
        Arc::new(ToolRegistry::new()), // no tools = pure inference
    );

    let store: Arc<dyn EventStore> = SqliteEventStore::in_memory().expect("in-memory store");
    let rt = LocalRuntime::new(store);
    let traj = rt.create_trajectory(None, "worker-face").await.unwrap();

    let plan = Plan {
        plan_id: "p".into(),
        goal: "review".into(),
        steps: vec![PlanStep {
            id: "review-0".into(),
            worker_role: "review".into(),
            instruction: "review the file".into(),
            depends_on: vec![],
            condition: StepCondition::Always,
        }],
    };
    let registry = WorkerRegistry::new().with_default(Arc::new(agent));

    let outcome = run_plan(
        rt.clone() as Arc<dyn Runtime>,
        traj,
        plan,
        registry,
        None,
        RunPlanConfig::default(),
        CancellationToken::new(),
    )
    .await
    .expect("run_plan completes with TarsAgent as the worker");

    // The step ran THROUGH TarsAgent's Worker impl and produced the parsed result.
    let ok = outcome.steps.iter().any(|s| {
        matches!(
            s,
            StepOutcome::Completed { step_id, result, .. }
                if step_id == "review-0"
                && matches!(result, tars_runtime::AgentMessage::PartialResult { summary, .. }
                    if summary == "reviewed lib.rs")
        )
    });
    assert!(
        ok,
        "review-0 must complete via TarsAgent-as-Worker with the worker JSON; got {:?}",
        outcome.steps
    );
}
