/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * The explicit per-call context passed from JS. All fields optional — an
 * empty `{}` yields a fresh single-user ("personal") context.
 */
export interface JsContext {
  /** Session id — the conversation / batch partition. Default `"local"`. */
  session?: string
  /**
   * Tenant id — the multi-tenant partition key (Doc 06 §8). Default
   * `"local"`.
   */
  tenant?: string
  /** Trace id for log correlation. Default: an auto-incremented `node-<n>`. */
  trace?: string
  /** Cohort tags surfaced on every emitted pipeline event. */
  tags?: Array<string>
}
/**
 * Load the process-global config **once** (Doc 06 §C1): providers + keys +
 * tier routing + any global `[roles]`, built from `~/.tars/config.toml`
 * (or `--tars_home` / `$TARS_HOME`; `home` overrides). Also eagerly builds
 * the shared provider registry so a bad provider/key surfaces here, at
 * startup, rather than on the first role resolution — and so opening a second
 * workspace never rebuilds it. Idempotent (a second call is a no-op).
 */
export declare function init(home?: string | undefined | null): void
/** Whether [`init`] has run (the global config is loaded). */
export declare function isInitialized(): boolean
/**
 * Resolve the tars home dir that [`init`] would read from
 * (`home` > `$TARS_HOME` > `~/.tars`). `None` only when no home is
 * discoverable at all.
 */
export declare function tarsHome(home?: string | undefined | null): string | null
/**
 * Smoke-test export — `import { hello } from '@leocaolab/tars-node'`
 * and `hello('world')` returns `'tars-node says hi, world'`. Pure
 * scaffolding sanity, kept for the Node-side smoke test.
 */
export declare function hello(name: string): string
/**
 * One failed bless assertion (Doc 28). `expected`/`actual` are JSON-encoded
 * strings so any value shape survives the FFI boundary.
 */
export interface BlessDrift {
  selector: string
  expected: string
  actual?: string
  reason: string
}
/** Result of [`blessCheck`]. `passed` is true when `drifts` is empty. */
export interface BlessResult {
  passed: boolean
  drifts: Array<BlessDrift>
}
/**
 * Load a committed bless file and check a completion's text against it
 * (Doc 28). `text` is decoded as JSON (chatty-tolerant), then each blessed
 * field is asserted. Mirrors `tars-py`'s `bless_check`.
 */
export declare function blessCheck(path: string, text: string): BlessResult
/**
 * Options for [`Pipeline::complete`]. Mirrors `tars-py`'s
 * `Pipeline.complete(**kwargs)` in camelCase.
 */
export interface CompleteOptions {
  /** Model id (e.g. "gemini-3.1-pro-preview"). Required. */
  model: string
  /** User-turn text. Mutually exclusive with `messages`. */
  user?: string
  /** System prompt. */
  system?: string
  /**
   * Pre-built message list as opaque JSON (`[{ role, content }, ...]`).
   * Mutually exclusive with `user`. M3 will replace with a typed
   * `MessageJs[]`; M2 keeps it `Value` so a Node caller with an
   * existing OpenAI-shape message list can drop it in.
   */
  messages?: any
  /** Cap on output tokens. Unset → provider default. */
  maxOutputTokens?: number
  /** Sampling temperature. Unset → provider default. */
  temperature?: number
  /** Enable thinking / extended reasoning (provider-specific). */
  thinking?: boolean
  /**
   * JSON Schema the model MUST conform to. Triggers the provider's
   * strict structured-output mode (Doc 01 §9).
   */
  responseSchema?: any
  /**
   * When `response_schema` is set, require strict conformance
   * (default true). False → schema is a hint, not enforced.
   */
  responseSchemaStrict?: boolean
  /** Free-form cohort tags surfaced in trajectory + event logs. */
  tags?: Array<string>
}
/** Result shape from [`Pipeline::complete`]. */
export interface CompleteResult {
  /** Aggregated assistant text. */
  text: string
  /** Token usage. */
  usage: UsageJs
  /** Model id the provider actually used (post-routing). */
  model?: string
  /**
   * Snake-case stop reason — "end_turn" / "max_tokens" /
   * "content_filter" / "tool_use" / "other".
   */
  stopReason?: string
}
/** Mirrors `tars_types::Usage` — per-call token counters. */
export interface UsageJs {
  inputTokens: number
  outputTokens: number
  cachedInputTokens: number
  cacheCreationTokens: number
  thinkingTokens: number
}
/**
 * Multi-workspace manager — the napi mirror of
 * `Mutex<HashMap<canonical_root, Tars>>` (Doc 06 §10). One per tool. Opening a
 * second workspace does **not** rebuild the global registry; `close` cancels +
 * drops the scope.
 */
export declare class Workspaces {
  /**
   * A manager for `tool` (e.g. `"arc"`). Its marker dir (`.<tool>/`) is what
   * [`Workspaces::open`] walks up to find.
   */
  constructor(tool: string)
  /**
   * Resolve `path` to a canonical workspace root (`.<tool>/` marker beats
   * `.git` — the monorepo rule; a bare dir with neither is opened as its own
   * root) and return the cached-or-newly-opened handle.
   */
  open(path: string): TarsHandle
  /** The already-open handle for `path`, or `null` if not open. Does not open. */
  get(path: string): TarsHandle | null
  /**
   * Close `path`: remove it from the map and cancel its scope. Returns
   * whether a handle was open. The scope's stores drain once any in-flight
   * job releases its `Arc` (deterministic `Drop`).
   */
  close(path: string): boolean
  /** Canonical roots currently open. */
  roots(): Array<string>
  /** Close every open workspace (cancel + drop each scope). */
  closeAll(): void
}
/**
 * A per-scope handle bound to one workspace (or standalone). Cheap to hold —
 * shares the underlying [`Tars`] scope by `Arc`, plus the explicit
 * [`RequestContext`] this handle carries into its calls (default: a fresh
 * single-user context; override with [`TarsHandle::context`]).
 */
export declare class TarsHandle {
  /**
   * A handle with no workspace (Doc 06 §7 standalone): store lives under
   * `~/.tars/standalone/<tool>/<session>/`. `session` defaults to `"local"`.
   */
  static standalone(tool: string, session?: string | undefined | null): TarsHandle
  /**
   * Open a handle for an explicit workspace `root` (no walk-up). Prefer
   * [`Workspaces::open`] for the cached/marker-resolving path; this is the
   * direct `--workspace <dir>` form.
   */
  static forWorkspace(tool: string, root: string): TarsHandle
  /**
   * A derived handle that carries the given explicit [`JsContext`] into every
   * call it makes (the FFI ctx boundary — see [`crate::ctx`]). Shares the same
   * underlying scope; only the context differs.
   */
  context(ctx: JsContext): TarsHandle
  /**
   * Layer 1 — the raw provider for `role` (no middleware), resolved via the
   * workspace `[roles]` map → global `[roles]` → tier → literal id.
   */
  provider(role: string): Provider
  /**
   * Layer 2 — the middleware-wrapped pipeline for `role`, with this scope's
   * event sink wired in. Same `complete()` surface as [`Provider`].
   */
  pipeline(role: string): Pipeline
  /** The canonical workspace root this handle is bound to. */
  root(): string
  /** The tool this handle was opened for. */
  get tool(): string
  /**
   * Cancel this scope's in-flight work (idempotent). The `Workspaces`
   * lifecycle owns removal from the map; this just fires the token.
   */
  close(): void
}
/**
 * Layer 1 provider handle — a raw backend bound to a role + this scope's ctx.
 * Same call surface as [`Pipeline`] so a caller can swap one for the other.
 */
export declare class Provider {
  /** The role name this provider was resolved for. */
  get role(): string
  /**
   * Single non-streaming chat completion against the raw provider. Re-scopes
   * `RUN_CONTEXT` with this handle's ctx at the boundary (Doc 06 §9).
   */
  complete(opts: CompleteOptions): Promise<CompleteResult>
}
/**
 * Pipeline handle. One per provider per Node process is the
 * expected pattern (cheap to clone via `Arc` but expensive to build
 * — `from_config_path` reads + parses TOML and constructs the
 * middleware chain). Construct once at startup and hold the handle
 * for the process's lifetime.
 */
export declare class Pipeline {
  /**
   * Construct from a `.arc/config.toml`-shaped file. `providerId`
   * names which `[providers.<id>]` block in the TOML to bind to.
   * Errors:
   *   - file missing / unreadable / not valid TOML → ConfigError
   *   - provider id absent from the config → ConfigError
   *   - provider construction fails (e.g. bad API key shape) →
   *     ProviderError
   */
  static fromConfigPath(path: string, providerId: string): Pipeline
  /**
   * Construct from inline TOML — same shape as a `.arc/config.toml`
   * file. Useful for tests + programmatic configs without a tmpfile
   * round-trip.
   */
  static fromStr(tomlText: string, providerId: string): Pipeline
  /** Provider id this pipeline wraps. */
  get id(): string
  /**
   * Single non-streaming chat-completion call.
   *
   * Builds a `ChatRequest` from `opts`, drives it through the
   * held middleware stack, drains the resulting event stream,
   * returns the aggregated text + usage + stop_reason. napi-rs
   * marshals this as a `Promise<CompleteResult>` to JS callers.
   */
  complete(opts: CompleteOptions): Promise<CompleteResult>
}
