/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Smoke-test export — `import { hello } from '@leocaolab/tars-node'`
 * and `hello('world')` returns `'tars-node says hi, world'`. Pure
 * scaffolding sanity, kept for the Node-side smoke test.
 */
export declare function hello(name: string): string
/**
 * Options for [`Pipeline::complete`]. Mirrors `tars-py`'s
 * `Pipeline.complete(**kwargs)` in camelCase.
 */
export interface CompleteOptions {
  /** Model id (e.g. "gemini-3.1-pro-preview"). Required. */
  model: string
  /** User-turn text. Mutually exclusive with `messages`. */
  user?: string
  /** System prompt. */
  system?: string
  /**
   * Pre-built message list as opaque JSON (`[{ role, content }, ...]`).
   * Mutually exclusive with `user`. M3 will replace with a typed
   * `MessageJs[]`; M2 keeps it `Value` so a Node caller with an
   * existing OpenAI-shape message list can drop it in.
   */
  messages?: any
  /** Cap on output tokens. Unset → provider default. */
  maxOutputTokens?: number
  /** Sampling temperature. Unset → provider default. */
  temperature?: number
  /** Enable thinking / extended reasoning (provider-specific). */
  thinking?: boolean
  /**
   * JSON Schema the model MUST conform to. Triggers the provider's
   * strict structured-output mode (Doc 01 §9).
   */
  responseSchema?: any
  /**
   * When `response_schema` is set, require strict conformance
   * (default true). False → schema is a hint, not enforced.
   */
  responseSchemaStrict?: boolean
  /** Free-form cohort tags surfaced in trajectory + event logs. */
  tags?: Array<string>
}
/** Result shape from [`Pipeline::complete`]. */
export interface CompleteResult {
  /** Aggregated assistant text. */
  text: string
  /** Token usage. */
  usage: UsageJs
  /** Model id the provider actually used (post-routing). */
  model?: string
  /**
   * Snake-case stop reason — "end_turn" / "max_tokens" /
   * "content_filter" / "tool_use" / "other".
   */
  stopReason?: string
}
/** Mirrors `tars_types::Usage` — per-call token counters. */
export interface UsageJs {
  inputTokens: number
  outputTokens: number
  cachedInputTokens: number
  cacheCreationTokens: number
  thinkingTokens: number
}
/**
 * Pipeline handle. One per provider per Node process is the
 * expected pattern (cheap to clone via `Arc` but expensive to build
 * — `from_config_path` reads + parses TOML and constructs the
 * middleware chain). Construct once at startup and hold the handle
 * for the process's lifetime.
 */
export declare class Pipeline {
  /**
   * Construct from a `.arc/config.toml`-shaped file. `providerId`
   * names which `[providers.<id>]` block in the TOML to bind to.
   * Errors:
   *   - file missing / unreadable / not valid TOML → ConfigError
   *   - provider id absent from the config → ConfigError
   *   - provider construction fails (e.g. bad API key shape) →
   *     ProviderError
   */
  static fromConfigPath(path: string, providerId: string): Pipeline
  /**
   * Construct from inline TOML — same shape as a `.arc/config.toml`
   * file. Useful for tests + programmatic configs without a tmpfile
   * round-trip.
   */
  static fromStr(tomlText: string, providerId: string): Pipeline
  /** Provider id this pipeline wraps. */
  get id(): string
  /**
   * Single non-streaming chat-completion call.
   *
   * Builds a `ChatRequest` from `opts`, drives it through the
   * held middleware stack, drains the resulting event stream,
   * returns the aggregated text + usage + stop_reason. napi-rs
   * marshals this as a `Promise<CompleteResult>` to JS callers.
   */
  complete(opts: CompleteOptions): Promise<CompleteResult>
}
